### ISSUE TITLE
parseHashParams doesn't get hash

### ISSUE THREAD

**Issue by redblobgames** [vtaits/url-search-utils#1]
`parseHashParams` is reading `window.location.hash.split('?')[1]` but `window.location.hash` can be a string like "#foo=5" (tried in chrome and firefox), so `window.location.hash.split('?')` will be `['#foo=5']` which doesn't have a value at `[1]`. It seems to work without the split call.

**Comment by vtaits** [comment]
Thank you for feedback!

`parseHashParams` is originally intended as a parser for get-like params of hash location, e.g.

```
http://awesome-spa.org/#/tasks/?status=opened&type=bug
```

Now I agree that `parseHashParams` is unsuitable name of api-method.

After about 12-15 hours i'll fix.

**Comment by vtaits** [comment]
Fix published in 0.2.0

**Comment by redblobgames** [comment]
Thank you! I am using this library in my project :) http://www.redblobgames.com/maps/mapgen2/embed.html
